package gr.uth.ece.dsel.aknn_hadoop;

public enum Metrics {
	NUM_CELLS, CELLS_PROC, DPC_COUNT, TOTAL_TPOINTS, SUMDIST, SUMDX, SUMDX_SUCCESS, SKIPPED_TPOINTS, HEUR1_SUCCESS, HEUR1_FAIL, HEUR2_SUCCESS, HEUR2_FAIL, HEUR3_SUCCESS, HEUR3_FAIL,
}